In [1]:
import torch
import numpy as np

In [3]:
# tensor initialize
data = [[1, 2], [3, 4], [5, 6]]
x_data = torch.tensor(data)

# numpy array to tensor
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)

# from another tesnor
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor : \n{x_ones}\n')
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor : \n{x_rand}\n')

Ones Tensor : 
tensor([[1, 1],
        [1, 1],
        [1, 1]])

Random Tensor : 
tensor([[0.6044, 0.8618],
        [0.8979, 0.1165],
        [0.7706, 0.2806]])



In [5]:
shape = (3, 4, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6449, 0.8309, 0.2603, 0.3329],
        [0.2261, 0.4226, 0.7825, 0.0693],
        [0.5357, 0.1738, 0.0183, 0.5780]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:
# Tensor Attributes
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [9]:
# Multiplying tensors
# element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# same with tensor.mul()
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[0.7396, 0.3725, 0.2093, 0.3311],
        [0.0421, 0.4235, 0.0143, 0.3784],
        [0.1831, 0.0038, 0.0586, 0.6482]]) 

tensor * tensor 
 tensor([[0.7396, 0.3725, 0.2093, 0.3311],
        [0.0421, 0.4235, 0.0143, 0.3784],
        [0.1831, 0.0038, 0.0586, 0.6482]])


In [10]:
# matrix multiplication
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# same with tensor.matmul()
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[1.6524, 0.9823, 0.9797],
        [0.9823, 0.8583, 0.6522],
        [0.9797, 0.6522, 0.8937]]) 

tensor @ tensor.T 
 tensor([[1.6524, 0.9823, 0.9797],
        [0.9823, 0.8583, 0.6522],
        [0.9797, 0.6522, 0.8937]])


In [11]:
# In-place operations
# use _ suffix
print(tensor, "\n")
tensor.add_(5)
print(tensor, "\n")
tensor.mul_(tensor)
print(tensor)

tensor([[0.8600, 0.6103, 0.4575, 0.5754],
        [0.2052, 0.6508, 0.1195, 0.6151],
        [0.4279, 0.0618, 0.2421, 0.8051]]) 

tensor([[5.8600, 5.6103, 5.4575, 5.5754],
        [5.2052, 5.6508, 5.1195, 5.6151],
        [5.4279, 5.0618, 5.2421, 5.8051]]) 

tensor([[34.3393, 31.4754, 29.7841, 31.0852],
        [27.0942, 31.9316, 26.2095, 31.5299],
        [29.4616, 25.6217, 27.4799, 33.6990]])


In [12]:
# Tensor to Numpy array
print(f't:{tensor}\n')
n = tensor.numpy()
print(f'n:{n}')

t:tensor([[34.3393, 31.4754, 29.7841, 31.0852],
        [27.0942, 31.9316, 26.2095, 31.5299],
        [29.4616, 25.6217, 27.4799, 33.6990]])

n:[[34.33926  31.475359 29.784103 31.085228]
 [27.094183 31.931618 26.209486 31.52985 ]
 [29.4616   25.621655 27.479929 33.699   ]]


In [14]:
# change in tensor reflects in Numpy aray
tensor.add_(5)
print(f't:{tensor}\n')
print(f'n:{n}')

t:tensor([[39.3393, 36.4754, 34.7841, 36.0852],
        [32.0942, 36.9316, 31.2095, 36.5299],
        [34.4616, 30.6217, 32.4799, 38.6990]])

n:[[39.33926  36.475357 34.784103 36.085228]
 [32.094185 36.931618 31.209486 36.52985 ]
 [34.4616   30.621655 32.479927 38.699   ]]


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

# change in numpy also reflects in tensor
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
